### ISSUE TITLE
Test suite assumes IDs are long

### ISSUE THREAD

**Issue by hylkevds** [opengeospatial/ets-sta10#40]
The test suite assumes IDs are Long (or int) and fails on implementations that use Strings as IDs, such as UUIDs.

```
org.json.JSONException: JSONObject["@iot.id"] is not a number.
	at org.json.JSONObject.getDouble(JSONObject.java:543)
	at org.json.JSONObject.getLong(JSONObject.java:612)
	at org.opengis.cite.sta10.sensingCore.Capability1Tests.readRelatedEntity(Capability1Tests.java:268)
```

I'll probably follow up with a pull request fixing the issue soon.

**Comment by hylkevds** [comment]
I've updated PR #32 to include the fixes.
I've also updated #28 (MultiDatastream tests), #27 (DataArray tests) and #26 (Geospatial tests)

**Comment by jordi-pallas** [comment]
Hi,

Is there any update on the status of this issue? We are currently testing a SensorThings API implementation that uses string-based identifiers, and the test suite still appears to assume that entity IDs are numeric (Long/int).

Is a fix planned for an upcoming release of the ETS?

<img width="1197" height="237" alt="Image" src="https://github.com/user-attachments/assets/038dc4a9-f854-42c5-821f-96a640edb0f2" />
